services:
  application:
    image: elixir-_learning:0.0.1
    container_name: elixir-_learning
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/elixir-_learning_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:14-bookworm
    container_name: elixir-_learning-postgres
    environment:
      - POSTGRES_DB=elixir-_learning_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - elixir-_learning_psql:/var/lib/postgresql/data
volumes:
  elixir-_learning_psql:
